a=10
b=3
result = a+b
print("a + b =",result)
result = a-b
print("a - b =",result)
result = a*b
print("a * b =",result)
result = a/b
print("a / b =",result)
result = a%b
print("a % b =",result)
result = a//b
print("a // b =",result)
result = a**b
print("a ** b =",result)
